<?xml version="1.0" encoding="utf-8"?><Database Name="TarlaDB" Class="dcTarlaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=TarlaDB;Integrated Security=True" SettingsObjectName="Tarla.Properties.Settings" SettingsPropertyName="TarlaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role" Id="ID1" Modifier="Sealed">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SettingPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BankPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FactorPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="RoleId" OtherKey="RoleId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User" Id="ID12" Modifier="Sealed">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product" Id="ID3" Modifier="Sealed">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Product_InvoiceDetail" Member="InvoiceDetails" ThisKey="ProductId" OtherKey="ProductId" Type="InvoiceDetail" />
      <Association Name="ProductGroup_Product" Member="ProductGroup" ThisKey="GroupId" OtherKey="GroupId" Type="ProductGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductGroups" Member="ProductGroups">
    <Type Name="ProductGroup" Id="ID2" Modifier="Sealed">
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="ProductGroup_Product" Member="Products" ThisKey="GroupId" OtherKey="GroupId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Sellers" Member="Sellers">
    <Type Name="Seller" Id="ID7" Modifier="Sealed">
      <Column Name="SellerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SellerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Seller_InvoiceDetail" Member="InvoiceDetails" ThisKey="SellerId" OtherKey="SellerId" Type="InvoiceDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Receivers" Member="Receivers">
    <Type Name="Receiver" Id="ID6" Modifier="Sealed">
      <Column Name="ReceiverId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Receiver_Invoice" Member="Invoices" ThisKey="ReceiverId" OtherKey="ReceiverId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Buyers" Member="Buyers">
    <Type Name="Buyer" Id="ID4" Modifier="Sealed">
      <Column Name="BuyerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Buyer_Book" Member="Books" ThisKey="BuyerId" OtherKey="BuyerId" Type="Book" />
      <Association Name="Buyer_Invoice" Member="Invoices" ThisKey="BuyerId" OtherKey="BuyerId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company" Id="ID5" Modifier="Sealed">
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Chief" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Company_BuyItem" Member="BuyItems" ThisKey="CompanyId" OtherKey="CompanyId" Type="BuyItem" />
    </Type>
  </Table>
  <Table Name="dbo.ItemGroups" Member="ItemGroups">
    <Type Name="ItemGroup" Id="ID9" Modifier="Sealed">
      <Column Name="ItemGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Unit1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Unit2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="ItemGroup_Item" Member="Items" ThisKey="ItemGroupId" OtherKey="ItemGroupId" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item" Id="ID8" Modifier="Sealed">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Item_BuyItem" Member="BuyItems" ThisKey="ItemId" OtherKey="ItemId" Type="BuyItem" />
      <Association Name="ItemGroup_Item" Member="ItemGroup" ThisKey="ItemGroupId" OtherKey="ItemGroupId" Type="ItemGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuyItems" Member="BuyItems">
    <Type Name="BuyItem" Id="ID10" Modifier="Sealed">
      <Column Name="BuyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuyDate" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Company_BuyItem" Member="Company" ThisKey="CompanyId" OtherKey="CompanyId" Type="Company" IsForeignKey="true" />
      <Association Name="Item_BuyItem" Member="Item" ThisKey="ItemId" OtherKey="ItemId" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log" Id="ID11" Modifier="Sealed">
      <Column Name="LogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogIn" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LogOut" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductPacking" Member="ProductPackings">
    <Type Name="ProductPacking" Id="ID13" Modifier="Sealed">
      <Column Name="PackingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackingType" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="ProductPacking_InvoiceDetail" Member="InvoiceDetails" ThisKey="PackingId" OtherKey="PackingId" Type="InvoiceDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Bank" Member="Banks">
    <Type Name="Bank" Id="ID14" Modifier="Sealed">
      <Column Name="BankId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BankNumber" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BankOwner" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BankDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Bank_Book" Member="Books" ThisKey="BankId" OtherKey="BankId" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.SystemLog" Member="SystemLogs">
    <Type Name="SystemLog" Modifier="Sealed">
      <Column Name="SysLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LogMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForiegnReceivers" Member="ForiegnReceivers">
    <Type Name="ForiegnReceiver" Id="ID15" Modifier="Sealed">
      <Column Name="F_ReceiverId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="F_ReceiverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="F_Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="F_Country" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ForiegnReceiver_Invoice" Member="Invoices" ThisKey="F_ReceiverId" OtherKey="F_ReceiverId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.FactorView" Member="FactorViews">
    <Type Name="FactorView" Id="ID16" Modifier="Sealed">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="BuyerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="ReceiverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_ReceiverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetSell" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message" Id="ID17" Modifier="Sealed">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book" Id="ID19">
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="BuyerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Bank_Book" Member="Bank" ThisKey="BankId" OtherKey="BankId" Type="Bank" IsForeignKey="true" />
      <Association Name="Buyer_Book" Member="Buyer" ThisKey="BuyerId" OtherKey="BuyerId" Type="Buyer" IsForeignKey="true" />
      <Association Name="PayType_Book" Member="PayType" ThisKey="PayTypeId" OtherKey="PayTypeId" Type="PayType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayTypes" Member="PayTypes">
    <Type Name="PayType" Id="ID20" Modifier="Sealed">
      <Column Name="PayTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="PayType_Book" Member="Books" ThisKey="PayTypeId" OtherKey="PayTypeId" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.BooksView" Member="BooksViews">
    <Type Name="BooksView" Id="ID18" Modifier="Sealed">
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="BuyerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.F_DetailsView" Member="F_DetailsViews">
    <Type Name="F_DetailsView" Id="ID21" Modifier="Sealed">
      <Column Name="DetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SellerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingType" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuyItemView" Member="BuyItemViews">
    <Type Name="BuyItemView" Id="ID22" Modifier="Sealed">
      <Column Name="BuyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyDate" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FactorDetailsView" Member="FactorDetailsViews">
    <Type Name="FactorDetailsView" Id="ID23" Modifier="Sealed">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="LicensePlate" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TotalWeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkerCost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TruckRental" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MiscCost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightNote" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DockWeightNote" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ReceiverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_ReceiverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetSell" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Paid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SellerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingType" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Setting" Member="Settings">
    <Type Name="Setting" Id="ID24" Modifier="Sealed">
      <Column Name="SettingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FactorAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FactorTel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Theme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FontSize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wallpaper" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceDetails" Member="InvoiceDetails">
    <Type Name="InvoiceDetail" Modifier="Sealed">
      <Column Name="DetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetWeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductPacking_InvoiceDetail" Member="ProductPacking" ThisKey="PackingId" OtherKey="PackingId" Type="ProductPacking" IsForeignKey="true" />
      <Association Name="Product_InvoiceDetail" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" />
      <Association Name="Seller_InvoiceDetail" Member="Seller" ThisKey="SellerId" OtherKey="SellerId" Type="Seller" IsForeignKey="true" />
      <Association Name="Invoice_InvoiceDetail" Member="Invoice" ThisKey="InvoiceId" OtherKey="InvoiceId" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Drivers" Member="Drivers">
    <Type Name="Driver" Id="ID25" Modifier="Sealed">
      <Column Name="DriverId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DriverName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LicenseId" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="LicensePlate" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Driver_Invoice" Member="Invoices" ThisKey="DriverId" OtherKey="DriverId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice" Modifier="Sealed">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="BuyerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DriverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalWeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkerCost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TruckRental" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MiscCost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightNote" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DockWeightNote" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ReceiverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_ReceiverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetSell" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Paid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Profit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Invoice_InvoiceDetail" Member="InvoiceDetails" ThisKey="InvoiceId" OtherKey="InvoiceId" Type="InvoiceDetail" />
      <Association Name="Buyer_Invoice" Member="Buyer" ThisKey="BuyerId" OtherKey="BuyerId" Type="Buyer" IsForeignKey="true" />
      <Association Name="Driver_Invoice" Member="Driver" ThisKey="DriverId" OtherKey="DriverId" Type="Driver" IsForeignKey="true" />
      <Association Name="ForiegnReceiver_Invoice" Member="ForiegnReceiver" ThisKey="F_ReceiverId" OtherKey="F_ReceiverId" Type="ForiegnReceiver" IsForeignKey="true" />
      <Association Name="Receiver_Invoice" Member="Receiver" ThisKey="ReceiverId" OtherKey="ReceiverId" Type="Receiver" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertLog" Method="InsertLog">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Login" Parameter="login" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateLog" Method="UpdateLog">
    <Parameter Name="LogId" Parameter="logId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Logout" Parameter="logout" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUsers" Method="DeleteUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckUserPass" Method="CheckUserPass">
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckUsersName" Method="CheckUsersName">
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetLoginId" Method="GetLoginId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistsSetting" Method="ExistsSetting">
    <Parameter Name="Exists" Parameter="exists" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistsUsers" Method="ExistsUsers">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistsRoles" Method="ExistsRoles">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertRole" Method="InsertRole">
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Settings" Parameter="settings" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="User" Parameter="user" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Bank" Parameter="bank" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Factor" Parameter="factor" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillRolesById" Method="FillRolesById">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="FillRolesByIdResult">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SettingPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BankPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FactorPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateRole" Method="UpdateRole">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Settings" Parameter="settings" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="User" Parameter="user" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Bank" Parameter="bank" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Factor" Parameter="factor" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillUsersById" Method="FillUsersById">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="FillUsersByIdResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateUsers" Method="UpdateUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillRoles" Method="FillRoles">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.DeleteGroups" Method="DeleteGroups">
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteProducts" Method="DeleteProducts">
    <Parameter Name="ProductId" Parameter="productId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillGroups" Method="FillGroups">
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.FillGroupsById" Method="FillGroupsById">
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.FillProductsById" Method="FillProductsById">
    <Parameter Name="ProductId" Parameter="productId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.FilterProductsByName" Method="FilterProductsByName">
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="NVarChar(30)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.InsertGroups" Method="InsertGroups">
    <Parameter Name="GroupName" Parameter="groupName" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertProducts" Method="InsertProducts">
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateProducts" Method="UpdateProducts">
    <Parameter Name="ProductId" Parameter="productId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateGroups" Method="UpdateGroups">
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GroupName" Parameter="groupName" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FilterProductsByGroup" Method="FilterProductsByGroup">
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="NVarChar(30)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.FilterProducts" Method="FilterProducts">
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="NVarChar(30)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.DeleteBuyer" Method="DeleteBuyer">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteCompany" Method="DeleteCompany">
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteReceiver" Method="DeleteReceiver">
    <Parameter Name="ReceiverId" Parameter="receiverId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSeller" Method="DeleteSeller">
    <Parameter Name="SellerId" Parameter="sellerId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillBuyer" Method="FillBuyer">
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.FillBuyerById" Method="FillBuyerById">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.FillCompanyById" Method="FillCompanyById">
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.FillCompany" Method="FillCompany">
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.FillReceiver" Method="FillReceiver">
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.FillReceiverById" Method="FillReceiverById">
    <Parameter Name="ReceiverId" Parameter="receiverId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.FillSeller" Method="FillSeller">
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.FillSellerById" Method="FillSellerById">
    <Parameter Name="SellerId" Parameter="sellerId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.InsertBuyer" Method="InsertBuyer">
    <Parameter Name="BuyerName" Parameter="buyerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertCompany" Method="InsertCompany">
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Chief" Parameter="chief" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertReceiver" Method="InsertReceiver">
    <Parameter Name="ReceiverName" Parameter="receiverName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSeller" Method="InsertSeller">
    <Parameter Name="SellerName" Parameter="sellerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBuyer" Method="UpdateBuyer">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BuyerName" Parameter="buyerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCompany" Method="UpdateCompany">
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Chief" Parameter="chief" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateReceiver" Method="UpdateReceiver">
    <Parameter Name="ReceiverId" Parameter="receiverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceiverName" Parameter="receiverName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSeller" Method="UpdateSeller">
    <Parameter Name="SellerId" Parameter="sellerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SellerName" Parameter="sellerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAddressSetting" Method="GetAddressSetting">
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="NVarChar(100)" Direction="InOut" />
    <Parameter Name="FactorAddress" Parameter="factorAddress" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Parameter Name="FactorTel" Parameter="factorTel" Type="System.String" DbType="NVarChar(20)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetThemeSetting" Method="GetThemeSetting">
    <Parameter Name="ThemeName" Parameter="themeName" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Parameter Name="FontSize" Parameter="fontSize" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteItemGroup" Method="DeleteItemGroup">
    <Parameter Name="ItemGroupId" Parameter="itemGroupId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteItems" Method="DeleteItems">
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillItemGroupById" Method="FillItemGroupById">
    <Parameter Name="ItemGroupId" Parameter="itemGroupId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID8" />
  </Function>
  <Function Name="dbo.FillItemGroup" Method="FillItemGroup">
    <ElementType IdRef="ID9" />
  </Function>
  <Function Name="dbo.FillItems" Method="FillItems">
    <ElementType IdRef="ID8" />
  </Function>
  <Function Name="dbo.FillItemsById" Method="FillItemsById">
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID8" />
  </Function>
  <Function Name="dbo.InsertItems" Method="InsertItems" IsComposable="true">
    <Parameter Name="ItemGroupId" Parameter="itemGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ItemName" Parameter="itemName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.InsertItemGroup" Method="InsertItemGroup">
    <Parameter Name="GroupName" Parameter="groupName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Unit1" Parameter="unit1" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Unit2" Parameter="unit2" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateItemGroup" Method="UpdateItemGroup">
    <Parameter Name="ItemGroupId" Parameter="itemGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GroupName" Parameter="groupName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Unit1" Parameter="unit1" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Unit2" Parameter="unit2" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateItems" Method="UpdateItems">
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ItemGroupId" Parameter="itemGroupId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ItemName" Parameter="itemName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteBuyItem" Method="DeleteBuyItem">
    <Parameter Name="BuyId" Parameter="buyId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillBuyItem" Method="FillBuyItem">
    <ElementType IdRef="ID10" />
  </Function>
  <Function Name="dbo.FillBuyItemById" Method="FillBuyItemById">
    <Parameter Name="BuyId" Parameter="buyId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID10" />
  </Function>
  <Function Name="dbo.InsertBuyItem" Method="InsertBuyItem">
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalPrice" Parameter="totalPrice" Type="System.Int32" DbType="Int" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBuyItem" Method="UpdateBuyItem">
    <Parameter Name="BuyId" Parameter="buyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalPrice" Parameter="totalPrice" Type="System.Int32" DbType="Int" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillLogs" Method="FillLogs">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID11" />
  </Function>
  <Function Name="dbo.FillUsers" Method="FillUsers">
    <ElementType IdRef="ID12" />
  </Function>
  <Function Name="dbo.GetLogId" Method="GetLogId">
    <Parameter Name="LogId" Parameter="logId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteRole" Method="DeleteRole">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckLoginPassById" Method="CheckLoginPassById">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateLoginPass" Method="UpdateLoginPass">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeletePacking" Method="DeletePacking">
    <Parameter Name="PackingId" Parameter="packingId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillPacking" Method="FillPacking">
    <ElementType IdRef="ID13" />
  </Function>
  <Function Name="dbo.FillPackingById" Method="FillPackingById">
    <Parameter Name="PackingId" Parameter="packingId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID13" />
  </Function>
  <Function Name="dbo.InsertPacking" Method="InsertPacking">
    <Parameter Name="PackingType" Parameter="packingType" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdatePacking" Method="UpdatePacking">
    <Parameter Name="PackingId" Parameter="packingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PackingType" Parameter="packingType" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteBank" Method="DeleteBank">
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillBank" Method="FillBank">
    <ElementType IdRef="ID14" />
  </Function>
  <Function Name="dbo.FillBankById" Method="FillBankById">
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID14" />
  </Function>
  <Function Name="dbo.InsertBank" Method="InsertBank">
    <Parameter Name="BankName" Parameter="bankName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BankNumber" Parameter="bankNumber" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="BankOwner" Parameter="bankOwner" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BankDesc" Parameter="bankDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBank" Method="UpdateBank">
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankName" Parameter="bankName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BankNumber" Parameter="bankNumber" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="BankOwner" Parameter="bankOwner" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BankDesc" Parameter="bankDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSystemLog" Method="InsertSystemLog">
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FormName" Parameter="formName" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillProducts" Method="FillProducts">
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.DeleteForeignReceiver" Method="DeleteForeignReceiver">
    <Parameter Name="F_ReceiverId" Parameter="f_ReceiverId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillForeignReceiver" Method="FillForeignReceiver">
    <ElementType IdRef="ID15" />
  </Function>
  <Function Name="dbo.FillForeignReceiverById" Method="FillForeignReceiverById">
    <Parameter Name="F_ReceiverId" Parameter="f_ReceiverId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID15" />
  </Function>
  <Function Name="dbo.InsertForeignReceiver" Method="InsertForeignReceiver">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Country" Parameter="country" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateForeignReceiver" Method="UpdateForeignReceiver">
    <Parameter Name="F_ReceiverId" Parameter="f_ReceiverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Country" Parameter="country" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteInvoice" Method="DeleteInvoice">
    <Parameter Name="InvoiceId" Parameter="invoiceId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FilterFactorByDate" Method="FilterFactorByDate">
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Date2" Parameter="date2" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID16" />
  </Function>
  <Function Name="dbo.FilterFactorById" Method="FilterFactorById">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID16" />
  </Function>
  <Function Name="dbo.GetMaxFactorId" Method="GetMaxFactorId">
    <Parameter Name="FactorId" Parameter="factorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMessage" Method="DeleteMessage">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertMessage" Method="InsertMessage">
    <Parameter Name="MessageText" Parameter="messageText" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillMessage" Method="FillMessage">
    <ElementType IdRef="ID17" />
  </Function>
  <Function Name="dbo.GetRandomMessage" Method="GetRandomMessage">
    <Parameter Name="MessageText" Parameter="messageText" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetBalanceById" Method="GetBalanceById">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Paid" Parameter="paid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="TotalPrice" Parameter="totalPrice" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FilterBooksViewByDate" Method="FilterBooksViewByDate">
    <Parameter Name="Date1" Parameter="date1" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Date2" Parameter="date2" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID18" />
  </Function>
  <Function Name="dbo.FilterBooksViewById" Method="FilterBooksViewById">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID18" />
  </Function>
  <Function Name="dbo.FillBookById" Method="FillBookById">
    <Parameter Name="BookId" Parameter="bookId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID19" />
  </Function>
  <Function Name="dbo.FillPayType" Method="FillPayType">
    <ElementType IdRef="ID20" />
  </Function>
  <Function Name="dbo.FillPayTypeById" Method="FillPayTypeById">
    <Parameter Name="PayTypeId" Parameter="payTypeId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID20" />
  </Function>
  <Function Name="dbo.DeleteBook" Method="DeleteBook">
    <Parameter Name="BookId" Parameter="bookId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertBook" Method="InsertBook">
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Int32" DbType="Int" />
    <Parameter Name="PayType" Parameter="payType" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BookDesc" Parameter="bookDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBook" Method="UpdateBook">
    <Parameter Name="BookId" Parameter="bookId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Int32" DbType="Int" />
    <Parameter Name="PayType" Parameter="payType" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BookDesc" Parameter="bookDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetFactorNetSell" Method="GetFactorNetSell">
    <Parameter Name="InvoiceId" Parameter="invoiceId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Netsell" Parameter="netsell" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="TotalPrice" Parameter="totalPrice" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Profit" Parameter="profit" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Loss" Parameter="loss" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateInvoiceNetSell" Method="UpdateInvoiceNetSell">
    <Parameter Name="InvoiceId" Parameter="invoiceId" Type="System.Int32" DbType="Int" />
    <Parameter Name="NetSell" Parameter="netSell" Type="System.Int32" DbType="Int" />
    <Parameter Name="Profit" Parameter="profit" Type="System.Int32" DbType="Int" />
    <Parameter Name="Loss" Parameter="loss" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetInvoiceDetails" Method="GetInvoiceDetails">
    <Parameter Name="InvoiceId" Parameter="invoiceId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID21" />
  </Function>
  <Function Name="dbo.GetUserPermissions" Method="GetUserPermissions">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Setting" Parameter="setting" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Bank" Parameter="bank" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="User" Parameter="user" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Factor" Parameter="factor" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillBuyItemByCompany" Method="FillBuyItemByCompany">
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID22" />
  </Function>
  <Function Name="dbo.FillBuyItembyDate" Method="FillBuyItembyDate">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.String" DbType="NVarChar(10)" />
    <ElementType IdRef="ID22" />
  </Function>
  <Function Name="dbo.GetBuyerNameAndPhone" Method="GetBuyerNameAndPhone">
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BuyerName" Parameter="buyerName" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Parameter Name="BuyerPhone" Parameter="buyerPhone" Type="System.String" DbType="NVarChar(12)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillFactorDetailsView" Method="FillFactorDetailsView">
    <Parameter Name="InvoiceId" Parameter="invoiceId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID23" />
  </Function>
  <Function Name="dbo.ExistsMessage" Method="ExistsMessage">
    <Parameter Name="Exists" Parameter="exists" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillSetting" Method="FillSetting">
    <ElementType IdRef="ID24" />
  </Function>
  <Function Name="dbo.UpdateSetting" Method="UpdateSetting">
    <Parameter Name="Company" Parameter="company" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FactorAddress" Parameter="factorAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FactortTell" Parameter="factortTell" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Theme" Parameter="theme" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FontSize" Parameter="fontSize" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SaveWallpaper" Method="SaveWallpaper">
    <Parameter Name="Wallpaper" Parameter="wallpaper" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetWallpaper" Method="GetWallpaper">
    <Parameter Name="Wallpaper" Parameter="wallpaper" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ClearWallpaper" Method="ClearWallpaper">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetLoginName" Method="GetLoginName">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(30)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSetting" Method="InsertSetting">
    <Parameter Name="Company" Parameter="company" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FactorAddress" Parameter="factorAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FactortTell" Parameter="factortTell" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Theme" Parameter="theme" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FontSize" Parameter="fontSize" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertInvoice" Method="InsertInvoice">
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DriverId" Parameter="driverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalWeight" Parameter="totalWeight" Type="System.Int32" DbType="Int" />
    <Parameter Name="WorkerCount" Parameter="workerCount" Type="System.Int32" DbType="Int" />
    <Parameter Name="WorkerCost" Parameter="workerCost" Type="System.Int32" DbType="Int" />
    <Parameter Name="TruckRental" Parameter="truckRental" Type="System.Int32" DbType="Int" />
    <Parameter Name="MiscCost" Parameter="miscCost" Type="System.Int32" DbType="Int" />
    <Parameter Name="WeightNote" Parameter="weightNote" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="DockWeightNote" Parameter="dockWeightNote" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ReceiverId" Parameter="receiverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="F_ReceiverId" Parameter="f_ReceiverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Discount" Parameter="discount" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalPrice" Parameter="totalPrice" Type="System.Int32" DbType="Int" />
    <Parameter Name="NetSell" Parameter="netSell" Type="System.Int32" DbType="Int" />
    <Parameter Name="Paid" Parameter="paid" Type="System.Int32" DbType="Int" />
    <Parameter Name="Profit" Parameter="profit" Type="System.Int32" DbType="Int" />
    <Parameter Name="Loss" Parameter="loss" Type="System.Int32" DbType="Int" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertInvoiceDetails" Method="InsertInvoiceDetails">
    <Parameter Name="InvoiceId" Parameter="invoiceId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductId" Parameter="productId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SellerId" Parameter="sellerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PackingId" Parameter="packingId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Weight" Parameter="weight" Type="System.Int32" DbType="Int" />
    <Parameter Name="Loss" Parameter="loss" Type="System.Int32" DbType="Int" />
    <Parameter Name="Qty" Parameter="qty" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Int32" DbType="Int" />
    <Parameter Name="NetWeight" Parameter="netWeight" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertDriver" Method="InsertDriver">
    <Parameter Name="DriverName" Parameter="driverName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="LicenseId" Parameter="licenseId" Type="System.String" DbType="NVarChar(11)" />
    <Parameter Name="LisensePlate" Parameter="lisensePlate" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateDriver" Method="UpdateDriver">
    <Parameter Name="DriverId" Parameter="driverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DriverName" Parameter="driverName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="LicenseId" Parameter="licenseId" Type="System.String" DbType="NVarChar(11)" />
    <Parameter Name="LisensePlate" Parameter="lisensePlate" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillDriverById" Method="FillDriverById">
    <Parameter Name="DriverId" Parameter="driverId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID25" />
  </Function>
  <Function Name="dbo.DeleteDriver" Method="DeleteDriver">
    <Parameter Name="DriverId" Parameter="driverId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillDrivers" Method="FillDrivers">
    <ElementType IdRef="ID25" />
  </Function>
  <Function Name="dbo.GetDriverLicensePlate" Method="GetDriverLicensePlate">
    <Parameter Name="DriverId" Parameter="driverId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LicensePlate" Parameter="licensePlate" Type="System.String" DbType="NVarChar(20)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>