<?xml version="1.0" encoding="utf-8"?><Database Name="TarlaDB" Class="dcTarlaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=TarlaDB;Integrated Security=True" SettingsObjectName="Tarla.Properties.Settings" SettingsPropertyName="TarlaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Setting" Member="Settings">
    <Type Name="Setting" Id="ID2">
      <Column Name="SettingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FactorAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FactorTel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Theme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FontSize" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role" Id="ID1">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SettingPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BankPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FactorPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="RoleId" OtherKey="RoleId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertLog" Method="InsertLog">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Login" Parameter="login" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateLog" Method="UpdateLog">
    <Parameter Name="LogId" Parameter="logId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Logout" Parameter="logout" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetLogId" Method="GetLogId">
    <Parameter Name="LogId" Parameter="logId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Logout" Parameter="logout" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUsers" Method="DeleteUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckUserPass" Method="CheckUserPass">
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckUsersName" Method="CheckUsersName">
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetLoginId" Method="GetLoginId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSetting" Method="InsertSetting">
    <Parameter Name="Company" Parameter="company" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FactorAddress" Parameter="factorAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FactortTell" Parameter="factortTell" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Theme" Parameter="theme" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FontSize" Parameter="fontSize" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistsSetting" Method="ExistsSetting">
    <Parameter Name="Exists" Parameter="exists" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistsUsers" Method="ExistsUsers">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistsRoles" Method="ExistsRoles">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertRole" Method="InsertRole">
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Settings" Parameter="settings" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="User" Parameter="user" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Bank" Parameter="bank" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Factor" Parameter="factor" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillRolesById" Method="FillRolesById">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="FillRolesByIdResult">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SettingPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BankPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FactorPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateRole" Method="UpdateRole">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Settings" Parameter="settings" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="User" Parameter="user" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Bank" Parameter="bank" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Factor" Parameter="factor" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillUsers" Method="FillUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="FillUsersResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.FillUsersById" Method="FillUsersById">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="FillUsersByIdResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateUsers" Method="UpdateUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillRoles" Method="FillRoles">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.FillSetting" Method="FillSetting">
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.UpdateSetting" Method="UpdateSetting">
    <Parameter Name="Company" Parameter="company" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FactorAddress" Parameter="factorAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FactortTell" Parameter="factortTell" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Theme" Parameter="theme" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FontSize" Parameter="fontSize" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetUserPermissions" Method="GetUserPermissions">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Setting" Parameter="setting" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Bank" Parameter="bank" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="User" Parameter="user" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Factor" Parameter="factor" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>